Repository stripe/stripe-ruby, pull requests merged in 2019-07, with the labels that each got.

#807 Add gem metadata
  stripe.gemspec
Labels: approved

#810 Better error message when passing non-string to custom method
  lib/stripe/api_resource.rb
  test/stripe/api_resource_test.rb
Labels: approved

#813 Convert library to use built-in `Net::HTTP`
  .rubocop.yml
  .rubocop_todo.yml
  README.md
  Rakefile
  lib/stripe.rb
  lib/stripe/connection_manager.rb
  lib/stripe/multipart_encoder.rb
  lib/stripe/resources/file.rb
  lib/stripe/stripe_client.rb
  lib/stripe/stripe_response.rb
  stripe.gemspec
  test/stripe/connection_manager_test.rb
  test/stripe/file_test.rb
  test/stripe/file_upload_test.rb
  test/stripe/multipart_encoder_test.rb
  test/stripe/stripe_client_test.rb
  test/stripe/stripe_response_test.rb
  test/test_helper.rb
Labels: breaking-api-change

#816 Make `CardError`'s `code` parameter named instead of positional
  lib/stripe/errors.rb
  lib/stripe/stripe_client.rb
Labels: approved, breaking-api-change

#821 Move Balance History to /v1/balance_transactions and add tests
  .travis.yml
  lib/stripe/resources/balance_transaction.rb
  test/stripe/balance_transaction_test.rb
  test/test_helper.rb
Labels: approved
